/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TasksIndexRouteImport } from "./routes/tasks/index"
import { Route as RequirementsIndexRouteImport } from "./routes/requirements/index"
import { Route as FeaturesIndexRouteImport } from "./routes/features/index"
import { Route as DecisionsIndexRouteImport } from "./routes/decisions/index"
import { Route as TasksIdRouteImport } from "./routes/tasks/$id"
import { Route as RequirementsIdRouteImport } from "./routes/requirements/$id"
import { Route as FeaturesIdRouteImport } from "./routes/features/$id"
import { Route as DecisionsIdRouteImport } from "./routes/decisions/$id"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: "/tasks/",
  path: "/tasks/",
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIndexRoute = RequirementsIndexRouteImport.update({
  id: "/requirements/",
  path: "/requirements/",
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: "/features/",
  path: "/features/",
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIndexRoute = DecisionsIndexRouteImport.update({
  id: "/decisions/",
  path: "/decisions/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: "/tasks/$id",
  path: "/tasks/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsIdRoute = RequirementsIdRouteImport.update({
  id: "/requirements/$id",
  path: "/requirements/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIdRoute = FeaturesIdRouteImport.update({
  id: "/features/$id",
  path: "/features/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsIdRoute = DecisionsIdRouteImport.update({
  id: "/decisions/$id",
  path: "/decisions/$id",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/decisions/$id": typeof DecisionsIdRoute
  "/features/$id": typeof FeaturesIdRoute
  "/requirements/$id": typeof RequirementsIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/decisions/": typeof DecisionsIndexRoute
  "/features/": typeof FeaturesIndexRoute
  "/requirements/": typeof RequirementsIndexRoute
  "/tasks/": typeof TasksIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/decisions/$id": typeof DecisionsIdRoute
  "/features/$id": typeof FeaturesIdRoute
  "/requirements/$id": typeof RequirementsIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/decisions": typeof DecisionsIndexRoute
  "/features": typeof FeaturesIndexRoute
  "/requirements": typeof RequirementsIndexRoute
  "/tasks": typeof TasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/decisions/$id": typeof DecisionsIdRoute
  "/features/$id": typeof FeaturesIdRoute
  "/requirements/$id": typeof RequirementsIdRoute
  "/tasks/$id": typeof TasksIdRoute
  "/decisions/": typeof DecisionsIndexRoute
  "/features/": typeof FeaturesIndexRoute
  "/requirements/": typeof RequirementsIndexRoute
  "/tasks/": typeof TasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/decisions/$id"
    | "/features/$id"
    | "/requirements/$id"
    | "/tasks/$id"
    | "/decisions/"
    | "/features/"
    | "/requirements/"
    | "/tasks/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/decisions/$id"
    | "/features/$id"
    | "/requirements/$id"
    | "/tasks/$id"
    | "/decisions"
    | "/features"
    | "/requirements"
    | "/tasks"
  id:
    | "__root__"
    | "/"
    | "/decisions/$id"
    | "/features/$id"
    | "/requirements/$id"
    | "/tasks/$id"
    | "/decisions/"
    | "/features/"
    | "/requirements/"
    | "/tasks/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisionsIdRoute: typeof DecisionsIdRoute
  FeaturesIdRoute: typeof FeaturesIdRoute
  RequirementsIdRoute: typeof RequirementsIdRoute
  TasksIdRoute: typeof TasksIdRoute
  DecisionsIndexRoute: typeof DecisionsIndexRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
  RequirementsIndexRoute: typeof RequirementsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/": {
      id: "/tasks/"
      path: "/tasks"
      fullPath: "/tasks/"
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/requirements/": {
      id: "/requirements/"
      path: "/requirements"
      fullPath: "/requirements/"
      preLoaderRoute: typeof RequirementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/features/": {
      id: "/features/"
      path: "/features"
      fullPath: "/features/"
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decisions/": {
      id: "/decisions/"
      path: "/decisions"
      fullPath: "/decisions/"
      preLoaderRoute: typeof DecisionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/$id": {
      id: "/tasks/$id"
      path: "/tasks/$id"
      fullPath: "/tasks/$id"
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/requirements/$id": {
      id: "/requirements/$id"
      path: "/requirements/$id"
      fullPath: "/requirements/$id"
      preLoaderRoute: typeof RequirementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/features/$id": {
      id: "/features/$id"
      path: "/features/$id"
      fullPath: "/features/$id"
      preLoaderRoute: typeof FeaturesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/decisions/$id": {
      id: "/decisions/$id"
      path: "/decisions/$id"
      fullPath: "/decisions/$id"
      preLoaderRoute: typeof DecisionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisionsIdRoute: DecisionsIdRoute,
  FeaturesIdRoute: FeaturesIdRoute,
  RequirementsIdRoute: RequirementsIdRoute,
  TasksIdRoute: TasksIdRoute,
  DecisionsIndexRoute: DecisionsIndexRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
  RequirementsIndexRoute: RequirementsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
